title: Sally Lee # Sally Lee
logo: https://congruentcounseling.com/wp-content/uploads/2018/10/Sally-Lee-Optimized.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I am a senior at the University of Maryland, Baltimore County (UMBC) studying Environmental Science and Geography. I have an interest in earth science and GIS and remote sensing.  
  <br><br>
  Please follow me in my journey! 
  <br><br>
  <a href="https://www.linkedin.com/in/sally-lee-36546315b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
